# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CardPaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('card_number', models.DecimalField(decimal_places=0, max_digits=18)),
                ('cvc', models.PositiveSmallIntegerField()),
                ('expiry_month', models.PositiveSmallIntegerField()),
                ('expiry_year', models.PositiveSmallIntegerField()),
                ('currency_code', models.CharField(max_length=4)),
                ('customer_order_code', models.CharField(max_length=100)),
                ('order_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaypalPaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('shopper_country_code', models.CharField(max_length=3)),
                ('currency_code', models.CharField(max_length=3)),
                ('customer_order_code', models.CharField(max_length=100)),
                ('order_description', models.CharField(max_length=100)),
                ('success_url', models.CharField(max_length=100)),
                ('pending_url', models.CharField(max_length=100)),
                ('failure_url', models.CharField(max_length=100)),
                ('cancellation_url', models.CharField(max_length=100)),
            ],
        ),
    ]
